server:
  port: 8081

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  datasource:
    username: root
    password: iemf
    url: jdbc:mysql://localhost:3306/userManagementSystem
    driver-class-name: com.mysql.cj.jdbc.Driver

